name: Node CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Test with coverage (for Sonar)
        run: make test-coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=NataliPele_qa-auto-engineer-javascript-project-87
            -Dsonar.organization=natalipele
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
